version: '3.4'

services:
  image-api:
    image: ${DOCKER_REGISTRY-}sampleimageapi
    build:
      context: .
      dockerfile: SampleImageApi/Dockerfile

  blazor-serverside:
    image: ${DOCKER_REGISTRY-}blazorserverside
    build:
      context: .
      dockerfile: BlazorServerSide/Dockerfile

